/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_Admin;
import javax.swing.JOptionPane;
/**
 *
 * @author Leonardo
 */
public class admin_Promo extends javax.swing.JFrame {
    
         private String marca;
    private double precioBase;

    
    private boolean promoAceptada = false;
    private double precioFinal;
    /**
     * Creates new form admin_Promo
     */
    public admin_Promo() {
         initComponents();
         setLocationRelativeTo(null);
    }
    public admin_Promo(String marca, double precioBase) {
        initComponents();
    setLocationRelativeTo(null);
    this.marca = marca;
    this.precioBase = precioBase;

    // Por defecto, el precio final es el base
    this.precioFinal = precioBase;

    jTextField1.setEditable(false);
    jTextField1.setText("");
    }
    private void mostrarMensaje() {
    // Calculamos el precio con posible descuento
     double precioConDescuento = precioBase;

    if (marca != null && marca.equalsIgnoreCase("TOYOTA")) {
        // 10% de descuento si la marca es TOYOTA
        precioConDescuento = precioBase * 0.90;
    }

    // Guardamos el precio final para usarlo después
    this.precioFinal = precioConDescuento;

    jTextField1.setEditable(false);

    String texto = "Precio base: S/ " + String.format("%.2f", precioBase)
                 + "   |   Precio con descuento: S/ " + String.format("%.2f", precioConDescuento);

    jTextField1.setText(texto);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logintxt = new javax.swing.JLabel();
        logintxt1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbIngresar = new javax.swing.JButton();
        jbIngresar1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logintxt.setBackground(new java.awt.Color(255, 255, 255));
        logintxt.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        logintxt.setForeground(new java.awt.Color(0, 153, 0));
        logintxt.setText("!Promoción 10% de descuento si la marca");

        logintxt1.setBackground(new java.awt.Color(255, 255, 255));
        logintxt1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        logintxt1.setForeground(new java.awt.Color(0, 153, 0));
        logintxt1.setText(" del carro que comprarás es TOYOTA!");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("¿Desea aceptar la promoción?");
        jLabel1.setAlignmentY(1.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(842, 64));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 190));

        jbIngresar.setText("Aceptar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        jbIngresar1.setText("Denegar");
        jbIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresar1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jbIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbIngresar1)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logintxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logintxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logintxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIngresar)
                    .addComponent(jbIngresar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(
        this,
        "Promoción aceptada.\nSe aplicará el 10% de descuento si el vehículo es TOYOTA.",
        "Promoción",
        JOptionPane.INFORMATION_MESSAGE
    );

    // Marca la promo como aceptada y muestra el precio con descuento
    this.promoAceptada = true;
    mostrarMensaje();
    }//GEN-LAST:event_jbIngresarActionPerformed

    private void jbIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresar1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(
        this,
        "Promoción rechazada.\nSe mantiene el precio base del vehículo.",
        "Promoción",
        JOptionPane.INFORMATION_MESSAGE
    );

    // No aplica promo: se deja el precio final igual al base
    this.promoAceptada = false;
    this.precioFinal = this.precioBase;

    this.dispose();
    }//GEN-LAST:event_jbIngresar1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_Promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_Promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_Promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_Promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_Promo().setVisible(true);
            }
        });
    }

    public boolean isPromoAceptada() {
    return promoAceptada;
    }

    public double getPrecioFinal() {
    return precioFinal;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JButton jbIngresar1;
    private javax.swing.JLabel logintxt;
    private javax.swing.JLabel logintxt1;
    // End of variables declaration//GEN-END:variables
}
