/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_Admin;
import Personas.Empleado;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author L34329
 */
public class gestionEmpleado extends javax.swing.JFrame {
        private List<Empleado> listaEmpleados = new ArrayList<>();

    /**
     * Creates new form gestionEmpleado
     */
    
    public gestionEmpleado() {
        initComponents();
    setLocationRelativeTo(null);
    configurarTablaEmpleados();
    }
    private void configurarTablaEmpleados() {
    javax.swing.table.DefaultTableModel modelo =
        new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {
                "Nombres",
                "Apellido Paterno",
                "Apellido Materno",
                "Dirección",
                "Teléfono",
                "Correo",
                "Rol"
            }
        );

    tblClientes.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo1 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();
        txtCodigo2 = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblPrecio2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtCodigo4 = new javax.swing.JTextField();
        lblPrecio3 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        btnRegistrar1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblPrecio1.setText("Telefono:");

        lblTitulo.setText("Apellido Paterno:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblPrecio2.setText("Correo:");

        lblAutor.setText("Apellido Materno:");

        lblPrecio3.setText("Rol:");

        lblPrecio.setText("Direccion: ");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblCodigo.setText("Nombres:");

        btnRegistrar1.setText("Siguiente");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        btnActualizar1.setText("Boleta");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dni", "Nombre", "Apellidos", "Telefono", "Correo"
            }
        ));
        tblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblTitulo)
                            .addComponent(lblAutor)
                            .addComponent(lblPrecio)
                            .addComponent(lblPrecio1)
                            .addComponent(lblPrecio2)
                            .addComponent(lblPrecio3))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(56, 56, 56)
                        .addComponent(btnRegistrar1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar1)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio1)
                    .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio2)
                            .addComponent(txtCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(btnRegistrar))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar1)
                            .addComponent(btnRegistrar1)
                            .addComponent(btnEliminar))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       int fila = tblClientes.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla.");
        return;
    }

    String nombres = txtCodigo.getText().trim();
    String apePaterno = txtTitulo.getText().trim();
    String apeMaterno = txtAutor.getText().trim();
    String direccion = txtPrecio.getText().trim();
    String telefono = txtCodigo1.getText().trim();
    String correo = txtCodigo4.getText().trim();
    String rol = txtCodigo2.getText().trim();

    if (nombres.isEmpty() || apePaterno.isEmpty() || apeMaterno.isEmpty()
            || direccion.isEmpty() || telefono.isEmpty()
            || correo.isEmpty() || rol.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    Empleado emp = listaEmpleados.get(fila);
    emp.setNombres(nombres);
    emp.setApellidoPaterno(apePaterno);
    emp.setApellidoMaterno(apeMaterno);
    emp.setDireccion(direccion);
    emp.setTelefono(telefono);
    emp.setCorreo(correo);
    emp.setRol(rol);

    cargarTabla();   // 👈 vuelve a pintarse la tabla
    limpiarCampos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
     int fila = tblClientes.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla.");
        return;
    }

    // Eliminamos de la lista
    listaEmpleados.remove(fila);

    // Volvemos a cargar la tabla desde la lista
    cargarTabla();

    // Limpiamos los campos de texto
    limpiarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String nombres = txtCodigo.getText().trim();
        String apePaterno = txtTitulo.getText().trim();
        String apeMaterno = txtAutor.getText().trim();
        String direccion = txtPrecio.getText().trim();
        String telefono = txtCodigo1.getText().trim();
        String correo = txtCodigo4.getText().trim();
        String rol = txtCodigo2.getText().trim();

        if (nombres.isEmpty() || apePaterno.isEmpty() || apeMaterno.isEmpty()
                || direccion.isEmpty() || telefono.isEmpty()
                || correo.isEmpty() || rol.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
    }//GEN-LAST:event_btnRegistrarActionPerformed
    Empleado emp = new Empleado(
                "",                // dni
                nombres,
                apePaterno,
                apeMaterno,
                direccion,
                telefono,
                correo,
                "",                // usuario
                "",                // contraseña
                rol
        );

        listaEmpleados.add(emp);

        javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tblClientes.getModel();

        modelo.addRow(new Object[] {
            emp.getNombres(),
            emp.getApellidoPaterno(),
            emp.getApellidoMaterno(),
            emp.getDireccion(),
            emp.getTelefono(),
            emp.getCorreo(),
            emp.getRol()
        });

        limpiarCampos();
    }                         
    
    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
        String nombres = txtCodigo.getText().trim();
    String apePaterno = txtTitulo.getText().trim();
    String apeMaterno = txtAutor.getText().trim();
    String direccion = txtPrecio.getText().trim();
    String telefono = txtCodigo1.getText().trim();
    String correo = txtCodigo4.getText().trim();
    String rol = txtCodigo2.getText().trim();

    if (nombres.isEmpty() || apePaterno.isEmpty() || apeMaterno.isEmpty()
            || direccion.isEmpty() || telefono.isEmpty()
            || correo.isEmpty() || rol.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    Empleado emp = new Empleado(
            "",                // dni
            nombres,
            apePaterno,
            apeMaterno,
            direccion,
            telefono,
            correo,
            "",                // usuario
            "",                // contraseña
            rol
    );

    listaEmpleados.add(emp);
    cargarTabla();     // 👈 importante
    limpiarCampos();
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
        String nombres    = txtCodigo.getText().trim();
    String apePaterno = txtTitulo.getText().trim();
    String apeMaterno = txtAutor.getText().trim();
    String direccion  = txtPrecio.getText().trim();
    String telefono   = txtCodigo1.getText().trim();
    String correo     = txtCodigo4.getText().trim();
    String rol        = txtCodigo2.getText().trim();

    if (nombres.isEmpty() || apePaterno.isEmpty() || apeMaterno.isEmpty()
            || direccion.isEmpty() || telefono.isEmpty()
            || correo.isEmpty() || rol.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Complete todos los campos antes de generar la boleta.");
        return;
    }

    String boleta = ""
        + "----------BOLETA DE EMPLEADO ---------------\n"
        + "Nombres         : " + nombres    + "\n"
        + "Apellido Paterno: " + apePaterno + "\n"
        + "Apellido Materno: " + apeMaterno + "\n"
        + "Dirección       : " + direccion  + "\n"
        + "Teléfono        : " + telefono   + "\n"
        + "Correo          : " + correo     + "\n"
        + "Rol             : " + rol        + "\n"
        + "-------------------------------------------------";

    javax.swing.JOptionPane.showMessageDialog(
            this,
            boleta,
            "Boleta de empleado",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnActualizar1ActionPerformed
    
    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {                                        
    int fila = tblClientes.getSelectedRow();
    if (fila != -1) {
        txtCodigo.setText(tblClientes.getValueAt(fila, 0).toString());
        txtTitulo.setText(tblClientes.getValueAt(fila, 1).toString());
        txtAutor.setText(tblClientes.getValueAt(fila, 2).toString());
        txtPrecio.setText(tblClientes.getValueAt(fila, 3).toString());
        txtCodigo1.setText(tblClientes.getValueAt(fila, 4).toString());
        txtCodigo4.setText(tblClientes.getValueAt(fila, 5).toString());
        txtCodigo2.setText(tblClientes.getValueAt(fila, 6).toString());
    }
}                                

    // Limpia los campos
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtPrecio.setText("");
        txtCodigo1.setText("");
        txtCodigo4.setText("");
        txtCodigo2.setText("");
        txtCodigo.requestFocus();
    }
    private void cargarTabla() {
   javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tblClientes.getModel();

    // Limpia todas las filas
    modelo.setRowCount(0);

    // Vuelve a cargar desde la lista
    for (Empleado emp : listaEmpleados) {
        modelo.addRow(new Object[] {
            emp.getNombres(),
            emp.getApellidoPaterno(),
            emp.getApellidoMaterno(),
            emp.getDireccion(),
            emp.getTelefono(),
            emp.getCorreo(),
            emp.getRol()
        });
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtCodigo2;
    private javax.swing.JTextField txtCodigo4;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
