/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_Admin;
import Gestion.GestionReportes1;
import Pagos.Pago;
import Pagos.PagoEfectivo;
import Pagos.PagoTarjeta;
import Pagos.PagoTransferencia;
import Ventas.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Personas.*;            
import Vehiculos.*;    

/**
 *
 * @author sebas
 */
public class gestionVentas extends javax.swing.JFrame {
    public gestionVentas() {
        initComponents();
    this.setTitle("Registro de Ventas");
    this.setLocationRelativeTo(null);
    this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    configurarTabla();
    llenarComboCotizaciones();
    listarVentas();
    llenarComboMetodos();

    // ⭐ AQUI SI TE DEJA ESCRIBIR ⭐
    jbVentaGeneral.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbVentaGeneralActionPerformed(evt);
        }
    });
    }
    private void llenarComboMetodos(){
        cboMetodo.removeAllItems();
        cboMetodo.addItem("EFECTIVO");
        cboMetodo.addItem("TARJETA");
        cboMetodo.addItem("TRANSFERENCIA");
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Cód. Venta");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Auto");
        modelo.addColumn("Total");
        modelo.addColumn("Abonado");
        modelo.addColumn("Saldo");
        modelo.addColumn("Estado");
        tblVentas.setModel(modelo);
    }

    private void llenarComboCotizaciones() {
        cboCotizacion.removeAllItems();
        cboCotizacion.addItem("Seleccione una cotización...");

        for (int i = 0; i < GestionReportes1.getContCotizaciones(); i++) {
            Cotizacion c = GestionReportes1.getListaCotizaciones()[i];
              if (c.getEstado() == EstadoCotizacion.APROBADO) {
            cboCotizacion.addItem(c);
        }
        }
    }
    public void listarVentas(){
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        modelo.setRowCount(0);

        for (int i = 0; i < GestionReportes1.getContVentas(); i++) {
            Venta v = GestionReportes1.getListaVentas()[i];
            Object[] fila = {
                v.getCodigoVenta(),
                v.getCliente().getNombres(),
                v.getVehiculo().getMarca(),
                "S/ " + v.getTotalVenta(),
                "S/ " + v.getTotalPagado(),      // Mostramos cuánto ha pagado
                "S/ " + v.getSaldoPendiente(),   // Mostramos cuánto debe
                v.estaPagada() ? "CANCELADO" : "PENDIENTE" // Estado deuda
            };
            modelo.addRow(fila);
        }
    }
    
    private double sumarVentasRecursivo(int indice) {
    if (indice >= GestionReportes1.getContVentas()) {
        return 0; // Caso base: ya no hay más ventas
    }

    Venta v = GestionReportes1.getListaVentas()[indice];
    return v.getTotalVenta() + sumarVentasRecursivo(indice + 1);
   }
       
        



  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jblCodigo = new javax.swing.JLabel();
        jblFecha = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cboCotizacion = new javax.swing.JComboBox();
        jblCotizacion = new javax.swing.JLabel();
        jblDetalle = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jblHistorial = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jbVentaGeneral = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        cboMetodo = new javax.swing.JComboBox<>();
        lblMonto = new javax.swing.JLabel();
        txtMontoPago = new javax.swing.JTextField();
        btnAgregarPago = new javax.swing.JButton();
        lblReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jblCodigo.setText("Codigo");
        jblCodigo.setToolTipText("");

        jblFecha.setText("Fecha");
        jblFecha.setToolTipText("");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        cboCotizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCotizacionActionPerformed(evt);
            }
        });

        jblCotizacion.setText("Cotizacion");

        jblDetalle.setText("Detalle");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jblHistorial.setText("Historial de Ventas");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblVentas);

        jScrollPane4.setEnabled(false);

        jbVentaGeneral.setText("Venta General");

        txtDetalle.setColumns(20);
        txtDetalle.setRows(5);
        jScrollPane1.setViewportView(txtDetalle);

        cboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metodo" }));
        cboMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMetodoActionPerformed(evt);
            }
        });

        lblMonto.setText("Monto Pago");

        btnAgregarPago.setText("AgregarPago");
        btnAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPagoActionPerformed(evt);
            }
        });

        lblReferencia.setText("Num.Tarjeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jblDetalle)
                            .addGap(53, 53, 53)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jblCodigo)
                                .addComponent(jblFecha)
                                .addComponent(jblCotizacion))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cboCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(btnRegistrar)
                                    .addGap(36, 36, 36)
                                    .addComponent(jbVentaGeneral))
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblReferencia)
                                    .addComponent(lblMonto))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMontoPago)
                                    .addComponent(txtReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                .addGap(122, 122, 122))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAgregarPago)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jblHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jblCodigo)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto)
                            .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblReferencia)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbVentaGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblCotizacion)
                                .addComponent(btnRegistrar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jblDetalle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnAgregarPago)))
                .addGap(51, 51, 51)
                .addComponent(jblHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        if (txtCodigo.getText().trim().isEmpty() || txtFecha.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar código y fecha.");
        return;
    }
    
    Object item = cboCotizacion.getSelectedItem();
    if (!(item instanceof Cotizacion)) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una cotización aprobada.");
        return;
    }

    try {
        // 1. Recuperar la cotización seleccionada
        Cotizacion cotiSeleccionada = (Cotizacion) item;
        String codVenta = txtCodigo.getText().trim();
        String fecha = txtFecha.getText().trim();

        // 2. Crear la venta
        Venta nuevaVenta = new Venta(codVenta, cotiSeleccionada, fecha);
        GestionReportes1.agregarVentas(nuevaVenta);

        // 3. Cambiar estado del vehículo a VENDIDO
        Vehiculo veh = cotiSeleccionada.getVehiculo();
        veh.setEstado(EstadoVehiculo.VENDIDO);

        // 4. Cambiar estado de la cotización a PROCESADO
        cotiSeleccionada.setEstado(EstadoCotizacion.PROCESADO);

        // 5. Refrescar la pantalla
        listarVentas();
        llenarComboCotizaciones();  // ya no saldrá esta cotización
        txtDetalle.setText("");
        txtCodigo.setText("");
        txtFecha.setText("");

        // 6. Armar COMPROBANTE
        Cliente cli = cotiSeleccionada.getCliente();
        Vendedor vend = cotiSeleccionada.getVendedor();

        String comprobante =
                "----------- COMPROBANTE DE VENTA -----------\n" +
                "Código de venta : " + codVenta + "\n" +
                "Fecha           : " + fecha + "\n\n" +
                "CLIENTE\n" +
                "Nombre          : " + cli.getNombres() + " "
                                   + cli.getApellidoPaterno() + " "
                                   + cli.getApellidoMaterno() + "\n\n" +
                "VEHÍCULO\n" +
                "Código          : " + veh.getCodigo() + "\n" +
                "Marca / Modelo  : " + veh.getMarca() + " " + veh.getModelo() + "\n" +
                "Color / Tipo    : " + veh.getColor() + " / " + veh.getTipo() + "\n\n" +
                "VENDEDOR\n" +
                "Nombre          : " + vend.getNombres() + " "
                                   + vend.getApellidoPaterno() + "\n\n" +
                "TOTAL A PAGAR   : S/ " + nuevaVenta.getTotalVenta() + "\n" +
                "--------------------------------------------";

        JOptionPane.showMessageDialog(
                this,
                comprobante,
                "Comprobante de Venta",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cboCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCotizacionActionPerformed

        Object item = cboCotizacion.getSelectedItem();
        if (item != null && item instanceof Cotizacion) {
            Cotizacion c = (Cotizacion) item;
            String resumen = "CLIENTE: " + c.getCliente().getNombres() + "\n"
                           + "AUTO: " + c.getVehiculo().getMarca() + " " + c.getVehiculo().getModelo() + "\n"
                           + "TOTAL: S/ " + c.getTotal();
            txtDetalle.setText(resumen);
        } else {
            txtDetalle.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cboCotizacionActionPerformed

    private void cboMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMetodoActionPerformed

    private void btnAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPagoActionPerformed
 
        int fila = tblVentas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una venta de la tabla para abonar.");
            return;
        }

        // 2. Validar monto
        if (txtMontoPago.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el monto a abonar.");
            return;
        }

        try {
            double monto = Double.parseDouble(txtMontoPago.getText().trim());
            String metodo = cboMetodo.getSelectedItem().toString();
            String referencia = txtReferencia.getText().trim(); // Opcional si agregaste este campo

            // 3. Buscar la Venta seleccionada en la memoria
            // Obtenemos el código de la venta de la columna 0 de la tabla
            String codigoVenta = tblVentas.getValueAt(fila, 0).toString();
            
            Venta ventaSeleccionada = null;
            for (int i = 0; i < GestionReportes1.getContVentas(); i++) {
                if (GestionReportes1.getListaVentas()[i].getCodigoVenta().equals(codigoVenta)) {
                    ventaSeleccionada = GestionReportes1.getListaVentas()[i];
                    break;
                }
            }

            if (ventaSeleccionada == null) return; // Seguridad

            // 4. Validar que no pague más de la deuda
            if (monto > ventaSeleccionada.getSaldoPendiente()) {
                JOptionPane.showMessageDialog(this, "El monto excede el saldo pendiente (S/ " + ventaSeleccionada.getSaldoPendiente() + ")");
                return;
            }

            // 5. Crear el objeto Pago según el método (Polimorfismo)
            Pago nuevoPago = null;
            String codPago = "P-" + System.currentTimeMillis(); // Generar código único simple

            switch (metodo) {
                case "EFECTIVO":
                    // Nota: Tu clase PagoEfectivo tenía campos de tarjeta por error, los dejamos vacíos ""
                    nuevoPago = new PagoEfectivo("", "", codPago, monto, "EFECTIVO", ventaSeleccionada);
                    break;
                case "TARJETA":
                    nuevoPago = new PagoTarjeta(codPago, monto, ventaSeleccionada, referencia, "VISA/MASTERCARD");
                    break;
                case "TRANSFERENCIA":
                    nuevoPago = new PagoTransferencia("Banco Generico", referencia, codPago, monto, "TRANSFERENCIA", ventaSeleccionada);
                    break;
            }

            // 6. Registrar el pago en la venta (Aquí se recalcula el saldo automáticamente)
            ventaSeleccionada.registrarPago(nuevoPago);

            // 7. Actualizar interfaz
            listarVentas(); // Refresca la tabla para ver el nuevo saldo
            txtMontoPago.setText("");
            txtReferencia.setText("");
            
            if (ventaSeleccionada.estaPagada()) {
                JOptionPane.showMessageDialog(this, "¡Pago registrado! La deuda ha quedado saldada.");
            } else {
                JOptionPane.showMessageDialog(this, "Abono registrado. Saldo restante: S/ " + ventaSeleccionada.getSaldoPendiente());
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar pago: " + e.getMessage());
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPagoActionPerformed
    
    private void jbVentaGeneralActionPerformed(java.awt.event.ActionEvent evt) {                                               
    double total = sumarVentasRecursivo(0);

    String boleta = ""
        + "----------- BOLETA GENERAL DE VENTAS -----------\n"
        + "Cantidad de ventas registradas: " + GestionReportes1.getContVentas() + "\n"
        + "Total acumulado de ventas     : S/ " + total + "\n"
        + "-----------------------------------------------";

    JOptionPane.showMessageDialog(
            this,
            boleta,
            "Boleta de Ventas",
            JOptionPane.INFORMATION_MESSAGE
    );
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPago;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cboCotizacion;
    private javax.swing.JComboBox<String> cboMetodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbVentaGeneral;
    private javax.swing.JLabel jblCodigo;
    private javax.swing.JLabel jblCotizacion;
    private javax.swing.JLabel jblDetalle;
    private javax.swing.JLabel jblFecha;
    private javax.swing.JLabel jblHistorial;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDetalle;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMontoPago;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
    }                                             

